//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "posts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub summary: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub category: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    pub author: Uuid,
    pub draft: Option<bool>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub read_time_millis: i64,
    #[sea_orm(column_type = "Text")]
    pub cover_image: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::post_categories::Entity",
        from = "Column::Category",
        to = "super::post_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PostCategories,
    #[sea_orm(has_many = "super::post_comments::Entity")]
    PostComments,
    #[sea_orm(has_many = "super::post_tags::Entity")]
    PostTags,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Author",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetDefault"
    )]
    Users,
}

impl Related<super::post_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostCategories.def()
    }
}

impl Related<super::post_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostComments.def()
    }
}

impl Related<super::post_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostTags.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::post_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::post_tags::Relation::Posts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
